### ISSUE TITLE
ItineraryDetail: Styling

### ISSUE THREAD

**Issue by arowla** [CommerceDataService/ITA_Principal_Travel#108]
As a user, I would like to see an attractive and clear layout of the Itinerary Detail information, so at a glance I can see and understand the most important information.
## Definition of Done
- [ ] Front end code written
## Acceptance Criteria
- [x] Can see Itinerary Details right away upon loading page
- [x] Can see itinerary dates larger and without labels (e.g. "March 1, 2016 - March 5, 2016")
- [x] Can prominently see locations travelled to
- [x] Can see just Principal's name and title, linked to PrincipalDetail page.
- [x] Do not see "Press" or "Press Note" under the Event Details
- [x] Can see labels distinguished from the information
- [x] Do not see fields which are "None"

**Comment by radhikabhatt26** [comment]
For "do not see press under event details", does that include press AND press notes?

**Comment by arowla** [comment]
Yes, I think it should. I'll edit the acceptance criteria.
