### ISSUE TITLE
Dashboard: Toggle Domestic/International

### ISSUE THREAD

**Issue by arowla** [CommerceDataService/ITA_Principal_Travel#188]
As a user, I would like to be able to see domestic and international travel on the dashboard separately, because the U.S. is an outlier and throws off all the charts.
## Definition of Done
- [ ] Back end code written
- [ ] Front end code written
- [ ] Tests written
## Acceptance Criteria
- [ ] I can go to the dashboard and see a toggle for Domestic/International
- [ ] I can change the view of the dashboard
- [ ] When I go to the dashboard, International is the default view
- [ ] When toggling, the map changes
- [ ] When toggling, the chart changes
- [ ] When toggling, the upcoming travel changes
- [ ] When toggling, "most recent" travel changes

**Comment by arowla** [comment]
International should be the default view.

**Comment by neka-io** [comment]
I'm going to add a domestic/international query param to the API endpoints to reduce processing on the front end and then rewrite the javascript to make ajax calls for domestic or international events and trips when the UI element is toggled. @radhikabhatt26 is going to create the toggle element. 
cc: @arowla
