### ISSUE TITLE
Itinerary Management

### ISSUE THREAD

**Issue by arowla** [CommerceDataService/ITA_Principal_Travel#54]
As an administrator, I want to be able to edit or delete the itineraries I have created.

**Comment by neka-io** [comment]
I'm breaking this task into two: the editing & deleting functionality and the user permission. This is the issue for the functionality.

**Comment by arowla** [comment]
## Definition of Done
- [x] Front end code written
- [x] Back end code written
- [ ] Integration tests written

## Acceptance Criteria
- [x] Can go to a list of itineraries and see an option to edit
- [x] Can choose to edit an itinerary and go to a form populated with that itinerary.
- [x] Can edit the existing itinerary in the form.
- [x] Can go to an itinerary and see an option to delete.
- [x] Can delete an itinerary and confirm that it has been deleted.
