### ISSUE TITLE
ItineraryForm: Country Filtering

### ISSUE THREAD

**Issue by arowla** [CommerceDataService/ITA_Principal_Travel#96]
As a user, I would like to be able to more quickly access a city by accessing a typeahead text box.
## Definition of Done
- [x] Front end code written
- [x] Back end code written
- [ ] Integration tests written
## Acceptance Criteria
- [x] Can start typing in the City box and see a filtered list of cities
- [x] Can confirm that the country and city are set correctly upon editing an itinerarye

**Comment by neka-io** [comment]
My understanding is that this kind of interactive and instantaneous filtering would have to take place client side using JS. The only way I can think of is to expose a query-able API endpoint for cities and countries and use Ajax to filter cities after country is selected.

**Comment by arowla** [comment]
That sounds about right. Maybe we could take advantage of something like typeahead.js here? (We might be able to get away with just a cities list (that includes country names), and forget hierarchical selection/filtering...
