### ISSUE TITLE
PrincipalsForm: Career Checkbox

### ISSUE THREAD

**Issue by arowla** [CommerceDataService/ITA_Principal_Travel#97]
As a user, I want to see a "Career" checkbox when I am creating or editing a Principal.
## Definition of Done
- [x] Front end code written
- [x] Back end code written
- [ ] Integration tests written
## Acceptance Criteria
- [x] Can log in and go to the principals creation/editing form
- [x] Can see a checkbox for "Career"
- [x] Can create a new principal with "Career" checked and see that it is saved in the record.
- [x] Can change the "Career" value on an existing principal from true to false, and back again.

**Comment by neka-io** [comment]
The checkbox is there but is being hidden by the US Design Standards styling for forms. I'll work on overwriting that.

**Comment by neka-io** [comment]
Opened an [issue](https://github.com/18F/web-design-standards/issues/1071)

**Comment by neka-io** [comment]
This issue is likely resolved with the implementation of bootstrap instead.
